[project]
name = "sample-proxy"
version = "0.1.6"
description = "A unified SOCKS and TCP tunnel proxy node."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
sample-proxy = "sample_proxy.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
